name: Publish

env:
  INSTALL_POETRY_VERSION: 1.*
  POETRY_INSTALLER_PARALLEL: false
  POETRY_VIRTUALENVS_CREATE: false

on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/tags
    tags: ["*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ env.INSTALL_POETRY_VERSION }}
      - name: Publish on Pypi
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish --build -u __token__ -p ${{ secrets.TEST_PYPI_SECRET }} -r testpypi
